apiVersion: v1
kind: Pod
metadata:
  name: video-scheduler
  labels:
    app: video-scheduler
spec:
  containers:
  - name: video-scheduler
    image: muharo/video_scheduler
    volumeMounts:
    - mountPath: /video
      name: video
    env:
    - name: BROKER_URL
      value: amqp://guest:guest@rabbitmq-service:5672
    - name: QUEUE_NAME
      value: myqueue
  volumes:
  - name: video
    hostPath:
      path: /shared/video