apiVersion: batch/v1
kind: Job
metadata:
  name: video-worker
spec:
  completions: 3072
  parallelism: 9
  template:
    metadata:
      name: video-worker
    spec:
      containers:
      - name: c
        image: muharo/video_worker
        volumeMounts:
        - mountPath: /video
          name: video
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: QUEUE
          value: myqueue
      volumes:
      - name: video
        hostPath:
          path: /shared/video
      restartPolicy: OnFailure
